import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kicks | Ecommerce site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-[#E7E7E3] pl-32 pr-32 pt-10"}>
        <Navbar />

        {children}
      </body>
    </html>
  );
}
