import { Inter } from "next/font/google";
import "./globals.css";

import { Navbar } from "@/components";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kicks | Ecommerce site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={
          inter.className + " bg-[#E7E7E3] lg:pl-20 lg:pr-20 lg:pt-10 pt-5 px-5"
        }
      >
        {children}
      </body>
    </html>
  );
}
